version: 2.1

orbs:
  docker: circleci/docker@2.4.0
  
jobs:
  build_and_release:
    docker:
      - image: cimg/node:24.1.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set up Git
          command: |
            git config --global user.email "dave@brimble.app"
            git config --global user.name "Muritala David"
      - run:
          name: Install pkg
          command: npm install -g pkg
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build CLI
          command: |
            npm ci
            npm run build
      - run:
          name: Build for target platforms
          command: npm run pre:release
          environment:
            PKG_OUTPUT: builds
      - run:
          name: Install ghr
          command: go install github.com/tcnksm/ghr@latest
      - run:
          name: Create GitHub Release
          command: |
            VERSION=${CIRCLE_TAG#refs/tags/}
            ghr -t ${GITHUB_TOKEN} \
                -u ${CIRCLE_PROJECT_USERNAME} \
                -r ${CIRCLE_PROJECT_REPONAME} \
                -c ${CIRCLE_SHA1} \
                -delete \
                -n "Release ${CIRCLE_SHA1}" \
                -b "Build artifacts: macos, linux & windows" \
                ${VERSION} ./builds/
      - run:
          name: Final clean up
          command: rm -rf builds

workflows:
  version: 2
  release_workflow:
    jobs:
      - build_and_release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /main/